require "validates/version"
require "validates/email_regexp"
require "validates/email_validator"
require "validates/slug_validator"
require "validates/url_validator"
require "validates/money_validator"
require "validates/inn_validator"
